services:
  postgres:
    image: postgres
    container_name: local_pgdb
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: /data/postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    ports:
      - "$POSTGRES_PORT:5432"
    restart: always
    networks:
      - pg_network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8888:80"
    restart: always
    networks:
      - pg_network

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  pg_network:
